## 1D - Tensors

In [1]:
import torch

In [3]:
a = torch.tensor([7,3,4,5,6])
a

tensor([7, 3, 4, 5, 6])

In [4]:
a.dtype

torch.int64

In [5]:
type(a)

torch.Tensor

In [6]:
a.type()

'torch.LongTensor'

In [12]:
b = torch.tensor([7.0,3.0,4.0,5.0,6.0], dtype = torch.int32)
b

tensor([7, 3, 4, 5, 6], dtype=torch.int32)

In [13]:
b.type()

'torch.IntTensor'

In [14]:
b.dtype

torch.int32

In [15]:
type(b)

torch.Tensor

In [16]:
b = torch.FloatTensor([7,3,4,5,6])
b

tensor([7., 3., 4., 5., 6.])

In [18]:
b.dtype

torch.float32

In [19]:
b.type()

'torch.FloatTensor'

In [25]:
b = torch.tensor([7,3,4,5,6])
b

tensor([7, 3, 4, 5, 6])

In [26]:
b = b.type(torch.FloatTensor)
b

tensor([7., 3., 4., 5., 6.])

In [28]:
b.type()

'torch.FloatTensor'

In [29]:
b.size()

torch.Size([5])

In [30]:
b.ndimension()

1

converting 1d to 2d tensors using view method

In [36]:
# columns
tensor1 = torch.tensor([1,2,3,4,5,6])
col_mat = tensor1.view(6,1)
col_mat

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [37]:
row_mat = tensor1.view(1,6)
row_mat

tensor([[1, 2, 3, 4, 5, 6]])

In [39]:
mat = tensor1.view(3,2)
mat

tensor([[1, 2],
        [3, 4],
        [5, 6]])

converting tensor to numpy array and viceversa

In [40]:
import numpy as np
numpy_array = np.array([1,2,3,4,5,6])
torch_tensor = torch.from_numpy(numpy_array)
torch_tensor

tensor([1, 2, 3, 4, 5, 6])

In [42]:
#tensor to numpy array
np_array = torch_tensor.numpy()
np_array

array([1, 2, 3, 4, 5, 6])

In [46]:
#pandas to numpy to tensor
import pandas as pd
series = pd.Series([1,2,3,4,5,6])
pandas_to_torch = torch.from_numpy(series.values)
pandas_to_torch

tensor([1, 2, 3, 4, 5, 6])

Indexing and Slicing

In [47]:
tensor1[0]

tensor(1)

In [48]:
tensor1[4]

tensor(5)

In [56]:
tensor1[4].item()

5

In [49]:
tensor1[:]

tensor([1, 2, 3, 4, 5, 6])

In [50]:
tensor1[:-1]

tensor([1, 2, 3, 4, 5])

In [55]:
tensor1[::4]

tensor([1, 5])

In [59]:
tensor1[0] = 1000
tensor1

tensor([1000,    2,    3,    4,    5,    6])

###Basic Operations

In [60]:
#additions
tensor1 = torch.tensor([1,2,3,4,5])
tensor2 = torch.tensor([10,6,7,12,9,])
add = tensor1+tensor2
add

tensor([11,  8, 10, 16, 14])

In [62]:
#subtraction
sub = tensor1 -tensor2
sub

tensor([-9, -4, -4, -8, -4])

In [63]:
#dot product
dot = tensor1 * tensor2
dot

tensor([10, 12, 21, 48, 45])

In [66]:
result = torch.dot(tensor1, tensor2)
result

tensor(136)

In [64]:
#vector multiplication with scalar
mul = tensor1 *3
mul

tensor([ 3,  6,  9, 12, 15])

In [67]:
#adding scalar to tensor
tensor1 = tensor1+1
tensor1

tensor([2, 3, 4, 5, 6])

In [74]:
a = torch.tensor([1.0,-1.0,1.0,-1.0])
mean_a = a.mean()
mean_a

tensor(0.)

In [75]:
a.max()

tensor(1.)

In [76]:
a.min()

tensor(-1.)

In [77]:
np.pi

3.141592653589793

In [78]:
x = torch.tensor([0,np.pi/2,np.pi])
y = torch.sin(x)

In [80]:
print(x)
print(y)

tensor([0.0000, 1.5708, 3.1416])
tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])


In [82]:
torch.linspace(-2,2, steps = 5)

tensor([-2., -1.,  0.,  1.,  2.])

In [83]:
x= torch.linspace(0, 2*np.pi, 100)
y = torch.sin(x)

In [87]:
import matplotlib as plt
plt.plot(x.numpy(), y.numpy)

AttributeError: module 'matplotlib' has no attribute 'plot'