In [1]:
import torch
a= [ [1,2,3],[4,5,6],[7,8,9]]
A = torch.tensor(a)
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [2]:
A.ndimension()

2

In [4]:
A.shape

torch.Size([3, 3])

In [5]:
A.size()

torch.Size([3, 3])

In [7]:
#number of elements
A.numel()

9

In [8]:
A[2][1]

tensor(8)

In [10]:
A[:2, :]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
#adding
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])
x+y

tensor([[ 6,  8],
        [10, 12]])

In [15]:
#multiplying with scalar
x = torch.tensor([[1,2], [3,4]])
x*3

tensor([[ 3,  6],
        [ 9, 12]])

In [16]:
#multiplication of 2 tensors
x*y

tensor([[ 5, 12],
        [21, 32]])

In [17]:
#matrix multiplication
A = torch.tensor([[0,1,1],[1,0,1]])
B = torch.tensor([[1,1],[1,1],[-1,1]])
c = torch.mm(A, B) #mm=> matrix multiplication

In [18]:
c

tensor([[0, 2],
        [0, 2]])